
import "./globals.css";
import Navbar from "./components/Navbar";
import Head from 'next/head';

interface Metadata {
  title: string;
  description: string;
}

export const metadata: Metadata = {
  title: "Cielo🌤",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body >
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
